"use server"

import { parsePoundsToPence } from "@/lib/apex/money"
import { createServerSupabase } from "@/lib/supabase/server"

export type TransactionFormState =
  { error?: string; success?: boolean } | undefined

// Adjustments are system-generated by Sync balance only — never user-entered
const ENTRY_KINDS = ["income", "expense", "transfer"] as const
type EntryKind = (typeof ENTRY_KINDS)[number]

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/

type ParsedEntry = {
  spaceId: string
  accountId: string
  kind: EntryKind
  amount: number
  description: string
  categoryId: string | null
  cardId: string | null
  occurredOn: string | null
  transferAccountId: string | null
}

function parseEntry(
  formData: FormData
): { error: string } | { entry: ParsedEntry } {
  const spaceId = String(formData.get("spaceId") ?? "")
  const kind = String(formData.get("kind") ?? "")
  const accountId = String(formData.get("accountId") ?? "")
  const description = String(formData.get("description") ?? "").trim()
  const categoryId = String(formData.get("categoryId") ?? "")
  const cardId = String(formData.get("cardId") ?? "")
  const occurredOn = String(formData.get("occurredOn") ?? "")
  const transferAccountId = String(formData.get("transferAccountId") ?? "")

  const amount = parsePoundsToPence(String(formData.get("amount") ?? ""))
  if (amount === null || amount <= 0) {
    return { error: "Enter a valid amount, like 12.50." }
  }
  if (!ENTRY_KINDS.includes(kind as EntryKind)) {
    return { error: "Pick income, expense or transfer." }
  }
  if (!spaceId || !accountId) return { error: "Pick an account." }
  if (!description) return { error: "Add a short description." }
  if (occurredOn && !DATE_RE.test(occurredOn)) {
    return { error: "That date doesn't look right." }
  }

  const isTransfer = kind === "transfer"
  if (isTransfer && !transferAccountId) {
    return { error: "Pick a destination account." }
  }
  if (isTransfer && transferAccountId === accountId) {
    return { error: "Transfers need two different accounts." }
  }

  return {
    entry: {
      spaceId,
      accountId,
      kind: kind as EntryKind,
      amount,
      description,
      // Transfers carry no category or card (docs/modules/apex.md decision 2)
      categoryId: !isTransfer && categoryId ? categoryId : null,
      cardId: !isTransfer && cardId ? cardId : null,
      occurredOn: occurredOn || null,
      transferAccountId: isTransfer ? transferAccountId : null,
    },
  }
}

/** Insert a transaction; the DB trigger moves account balances. */
export async function createTransaction(
  _prev: TransactionFormState,
  formData: FormData
): Promise<TransactionFormState> {
  const parsed = parseEntry(formData)
  if ("error" in parsed) return { error: parsed.error }
  const { entry } = parsed

  const supabase = await createServerSupabase()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: "Not signed in." }

  const { error } = await supabase.from("transactions").insert({
    space_id: entry.spaceId,
    account_id: entry.accountId,
    kind: entry.kind,
    amount: entry.amount,
    description: entry.description,
    category_id: entry.categoryId,
    card_id: entry.cardId,
    // Omitted when empty so the DB default (today) applies
    ...(entry.occurredOn ? { occurred_on: entry.occurredOn } : {}),
    transfer_account_id: entry.transferAccountId,
    created_by: user.id,
  })

  if (error) return { error: friendlyDbError(error.message) }
  return { success: true }
}

/** Update a transaction in place; the DB trigger reverts and reapplies balances. */
export async function updateTransaction(
  _prev: TransactionFormState,
  formData: FormData
): Promise<TransactionFormState> {
  const transactionId = String(formData.get("transactionId") ?? "")
  if (!transactionId) return { error: "Missing transaction." }

  const parsed = parseEntry(formData)
  if ("error" in parsed) return { error: parsed.error }
  const { entry } = parsed

  const supabase = await createServerSupabase()

  const { error, count } = await supabase
    .from("transactions")
    .update(
      {
        account_id: entry.accountId,
        kind: entry.kind,
        amount: entry.amount,
        description: entry.description,
        category_id: entry.categoryId,
        card_id: entry.cardId,
        ...(entry.occurredOn ? { occurred_on: entry.occurredOn } : {}),
        transfer_account_id: entry.transferAccountId,
      },
      { count: "exact" }
    )
    .eq("id", transactionId)
    .eq("space_id", entry.spaceId)
    // Adjustments are system-owned; editing one would corrupt the sync audit trail
    .neq("kind", "adjustment")
    .is("deleted_at", null)

  if (error) return { error: friendlyDbError(error.message) }
  if (count === 0) return { error: "Transaction not found." }
  return { success: true }
}

/** Soft delete: stamps deleted_at AND deleted_by in one UPDATE — RLS rejects unstamped deletes. */
export async function softDeleteTransaction(
  transactionId: string
): Promise<{ error?: string }> {
  const supabase = await createServerSupabase()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: "Not signed in." }

  const { error, count } = await supabase
    .from("transactions")
    .update(
      { deleted_at: new Date().toISOString(), deleted_by: user.id },
      { count: "exact" }
    )
    .eq("id", transactionId)
    // Adjustments are the Sync-balance audit trail. Editing one was already
    // blocked; deleting one reverted the correction and silently moved the
    // balance, which is the same corruption by another route.
    .neq("kind", "adjustment")
    .is("deleted_at", null)

  if (error) return { error: friendlyDbError(error.message) }
  if (count === 0) {
    return { error: "Transaction not found, or it's a system balance sync." }
  }
  return {}
}

function friendlyDbError(message?: string) {
  if (!message) return "Something went wrong. Try again."
  return message.replace(/^.*?exception:\s*/i, "")
}
